# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BreadBoardApps.com
email: email@BreadBoardApps.com
description: > # this means to ignore newlines until "baseurl:"
 BreadBoardApps - we build apps for Windows 10, iOS, and Android
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://BreadBoardApps.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""



# Build settings
markdown: kramdown
permalink: pretty
theme: minima

paginate: 10
paginate_path: "/journal/page:num/"