theme: minima

title: BreadBoardApps.com
email: email@BreadBoardApps.com
description: > # this means to ignore newlines until "baseurl:"
 Copyright © BreadBoardApps 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://BreadBoardApps.com" # the base hostname & protocol for your site
